name = "anispace-oauth-proxy"
main = "oauth-proxy.js"
compatibility_date = "2024-01-01"
account_id = "e3859153513e18ee3e56cc9345846356"

[vars]
# 非敏感配置可放这里
# 敏感信息（CLIENT_SECRET）请在 Cloudflare Dashboard 中配置为 Secrets
